set nocompatible              " be iMproved, required
filetype plugin on                 " required
set omnifunc=syntaxcomplete#Complete

" Plugins {{{
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
"Plugin 'valloric/youcompleteme'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'flazz/vim-colorschemes'
Plugin 'tpope/vim-fugitive'
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-endwise'
Plugin 'elixir-lang/vim-elixir'
Plugin 'mattn/emmet-vim'
Plugin 'tpope/vim-rails'
Plugin 'mileszs/ack.vim'
Plugin 'mbbill/undotree'
Plugin 'pangloss/vim-javascript'
Plugin 'yuezk/vim-js'
Plugin 'maxmellon/vim-jsx-pretty'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" Put your non-Plugin stuff after this line
"}}}

"Ack.vim settings {{{
cnoreabbrev Ack Ack!
nnoremap <Leader>f :Ack!<Space>
"}}}

" Nerdtree {{{ 
autocmd StdinReadPre * let s:std_in=1
map <BS> :NERDTreeToggle<CR>
"}}}

" Emmet {{{
let g:user_emmet_leader_key='<C-Z>' "remaps trigger keys to ctrl-z
" }}}

" CtrlP settings {{{
let g:ctrlp_match_window = 'bottom,order:ttb'
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0
let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden -g ""'
"}}}

" undotree settings {{{
nnoremap <Leader>u :UndotreeToggle<cr>
"}}}
"

" General Vim settings {{{
syntax enable           " enable syntax processing
"set number              " show line numbers
" turn hybrid line numbers on
set number relativenumber
set nu rnu
set cursorline          " highlight current line
filetype indent on      " load filetype-specific indent files
"set spell spelllang=en_us
set showmatch           " highlight matching [{()}]
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set ignorecase
set smartcase
set tabstop=2       " number of visual spaces per TAB
set softtabstop=2   " number of spaces in tab when editing
set shiftwidth=2
set autoindent
set smartindent
set cindent
set smarttab
set expandtab       " tabs are spaces
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.
"set foldenable          " enable folding
"set foldlevelstart=10   " open most folds by default
"set foldnestmax=10      " 10 nested fold max
set backspace=indent,eol,start
" fold vimrc
"set foldmethod=marker
"set foldlevel=0
"set modelines=1
"set foldmethod=indent   " fold based on indent level
colorscheme molokai

let g:mapleader=","  " leader is comma
" Return inserts newline and goes back to command mode
nmap <CR> o<Esc>

"Open new split panes to the right and bottom, which feels more natural
set splitbelow
set splitright

" save session
nnoremap <leader>s :mksession<CR>
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
"move vertically by visual line
nnoremap j gj
nnoremap k gk
" space open/closes folds
"nnoremap <space> za

" edit vimrc/zshrc and load vimrc bindings
nnoremap <leader>ev :vsp $MYVIMRC<CR>
nnoremap <leader>ez :vsp ~/.zshrc<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>

"make jk == esc
inoremap jk <esc>

" Reselect visual block after indent/outdent
vnoremap < <gv
vnoremap > >gv

map :Q :q
map :W :w
map <C-c> a<C-c><ESC>
vnoremap <C-C> :w !pbcopy<CR><CR>

"let g:user_emmet_settings=webapi#json#decode(join(readfile(expand('~/.snippets_custom.json')), "\n"))
nnoremap <leader><space> :nohlsearch<CR>
"}}}

" vim:foldmethod=marker:foldlevel=0
